import type { Project } from "./types";

// 로컬/미연동 상태에서 UI를 완전히 구동하기 위한 시드 데이터.
// Notion·Supabase 연동 시 동일한 Project 형태를 동기화로 채운다.

const IMG = (n: number) => `/portfolio/r${((n - 1) % 3) + 1}.webp`;

function rooms(no: number, list: string[]) {
  return list.map((room, i) => ({
    id: `${no}-${i}`,
    room,
    imageUrl: IMG(no + i),
    sortOrder: i,
  }));
}

export const SEED_PROJECTS: Project[] = [
  {
    no: 421,
    notionPageId: "seed-421",
    title: "淸輝齋",
    subtitle: "맑게 빛나는 집",
    apartment: "용산파크타워",
    sizeCategory: "40PY",
    type: "주상복합",
    areaSupply: "47.97평형",
    areaExclusive: "37.75평",
    completionYear: 2009,
    region: "서울시 용산구 한강로동",
    period: "11주",
    coverUrl: IMG(1),
    sortOrder: 1,
    images: rooms(421, ["거실", "주방", "침실", "드레스룸", "욕실", "현관"]),
  },
  {
    no: 388,
    notionPageId: "seed-388",
    title: "Sequentopia",
    subtitle: "이어지는 풍경",
    apartment: "반포자이",
    sizeCategory: "50PY~",
    type: "아파트",
    areaSupply: "59.20평형",
    areaExclusive: "49.91평",
    completionYear: 2008,
    region: "서울시 서초구 반포동",
    period: "13주",
    coverUrl: IMG(3),
    sortOrder: 2,
    images: rooms(388, ["거실", "주방", "복도", "침실", "서재", "욕실"]),
  },
  {
    no: 365,
    notionPageId: "seed-365",
    title: "Warm Layers",
    subtitle: "따뜻한 결",
    apartment: "마포래미안푸르지오",
    sizeCategory: "30PY",
    type: "아파트",
    areaSupply: "34.00평형",
    areaExclusive: "25.71평",
    completionYear: 2014,
    region: "서울시 마포구 아현동",
    period: "9주",
    coverUrl: IMG(5),
    sortOrder: 3,
    images: rooms(365, ["거실", "주방", "침실", "욕실", "발코니"]),
  },
  {
    no: 342,
    notionPageId: "seed-342",
    title: "Quiet Stone",
    subtitle: "고요한 돌의 질감",
    apartment: "헬리오시티",
    sizeCategory: "30PY",
    type: "아파트",
    areaSupply: "33.10평형",
    areaExclusive: "24.80평",
    completionYear: 2018,
    region: "서울시 송파구 가락동",
    period: "10주",
    coverUrl: IMG(4),
    sortOrder: 4,
    images: rooms(342, ["거실", "주방", "복도", "침실", "욕실"]),
  },
  {
    no: 318,
    notionPageId: "seed-318",
    title: "Oak Frame",
    subtitle: "오크의 프레임",
    apartment: "아크로리버파크",
    sizeCategory: "40PY",
    type: "아파트",
    areaSupply: "43.20평형",
    areaExclusive: "34.10평",
    completionYear: 2016,
    region: "서울시 서초구 반포동",
    period: "12주",
    coverUrl: IMG(6),
    sortOrder: 5,
    images: rooms(318, ["거실", "주방", "침실", "드레스룸", "서재", "욕실"]),
  },
  {
    no: 295,
    notionPageId: "seed-295",
    title: "Soft Minimal",
    subtitle: "부드러운 미니멀",
    apartment: "e편한세상",
    sizeCategory: "20PY",
    type: "아파트",
    areaSupply: "24.80평형",
    areaExclusive: "18.10평",
    completionYear: 2012,
    region: "경기도 성남시 분당구",
    period: "7주",
    coverUrl: IMG(2),
    sortOrder: 6,
    images: rooms(295, ["거실", "주방", "침실", "욕실"]),
  },
  {
    no: 271,
    notionPageId: "seed-271",
    title: "Compact Living",
    subtitle: "작지만 충분한",
    apartment: "마곡엠밸리",
    sizeCategory: "10PY",
    type: "오피스텔",
    areaSupply: "12.40평형",
    areaExclusive: "9.20평",
    completionYear: 2017,
    region: "서울시 강서구 마곡동",
    period: "5주",
    coverUrl: IMG(3),
    sortOrder: 7,
    images: rooms(271, ["거실", "주방", "욕실"]),
  },
  {
    no: 248,
    notionPageId: "seed-248",
    title: "Garden House",
    subtitle: "정원이 있는 집",
    apartment: "판교 단독주택",
    sizeCategory: "50PY~",
    type: "단독주택",
    areaSupply: "62.00평형",
    areaExclusive: "55.00평",
    completionYear: 2020,
    region: "경기도 성남시 분당구 판교동",
    period: "20주",
    coverUrl: IMG(1),
    sortOrder: 8,
    images: rooms(248, ["거실", "주방", "복도", "침실", "드레스룸", "서재", "욕실", "발코니"]),
  },
];
